### ISSUE TITLE
Make this work with Elastic CI stack for AWS 5.0.0

### ISSUE THREAD

**Issue by xiaket** [mikeknox/aws-paramstore-secrets-buildkite-plugin#18]
ECI for AWS 5.0.0 just got released. We need to make sure that this solution still works.

**Comment by vgrigoruk** [comment]
We're using elastic CI stack v5.3.0 and it works for us :)

**Comment by xiaket** [comment]
Thanks @vgrigoruk , maybe we should upgrade ours now :)
