### ISSUE TITLE
 /usr/local/buildkite-aws-stack/plugins/aws-paramstore-secrets/hooks/environment: No such file or directory

### ISSUE THREAD

**Issue by mdesouky** [mikeknox/aws-paramstore-secrets-buildkite-plugin#24]
After installation using the snippet provided and putting it in the bootstrap script, I'm getting this error
`/etc/buildkite-agent/hooks/environment: line 136: /usr/local/buildkite-aws-stack/plugins/aws-paramstore-secrets/hooks/environment: No such file or directory`

I connected to the instance and run the installation commands myself as `root` and it was all successful but indeed the script the plugin is looking to source (which is line 136) 
`f [[ -n "${AWS_SSM_SECRETS_PLUGIN_ENABLED:-}" && "${AWS_SSM_SECRETS_PLUGIN_ENABLED:-}" == "1" ]]
then
  source /usr/local/buildkite-aws-stack/plugins/aws-paramstore-secrets/hooks/environment`
  doesn't actually exist, not sure if I am missing something or there has been a problem with the installation

**Comment by mdesouky** [comment]
I found that [configure.sh](https://github.com/mikeknox/aws-paramstore-secrets-buildkite-plugin/blob/master/configure.sh) breaks at [line 13](https://github.com/mikeknox/aws-paramstore-secrets-buildkite-plugin/blob/master/configure.sh#L13) for some reason, so basically the hooks don't get installed

**Comment by mdesouky** [comment]
I'm using `v5.6.1`

**Comment by mdesouky** [comment]
solved by doing `cp -r hooks/ /usr/local/buildkite-aws-stack/plugins/aws-paramstore-secrets/` but when running any pipeline, it's stuck on `Running global pre-checkout hook` line for over 10 minutes

**Comment by mikeknox** [comment]
thanks,l Mohamed,
I'm spinning up a v5.6 stack to investigate this as well.

**Comment by mdesouky** [comment]
@mikeknox Any Luck ?

**Comment by mikeknox** [comment]
Mohamed,
Are you able to retest with the latest version of the plugin?
My testing hasn't shown issues so far, we did a small patch very recently to address an issue that is slightly similar to what you've described.

**Comment by mikeknox** [comment]
Closing as we've been unable to replicate the issue.
Please re-open if there are further updates.

**Comment by jay-alderton** [comment]
I'm encountering the exact same problem from a fresh configuration. The error message is identical.

* My bootstrap script contains only the code snippet from the readme.md (updated to 0.9.3).
* Permissions are set up in IAM correctly.
* Using Elastic CI stack v5.9.0.
* `/vendors/buildkite/global/ssh/key` has been set up.
* `/vendors/buildkite/global/env/TEST_VARIABLE` has been set up.
* There are no environment hooks or `private_ssh_key` present in the S3 bucket.

Notably, even though there is an SSH key in SSM, I get the following error when the pipeline runs as well:
`The repository "git@bitbucket.org:reponame.git" appears to use SSH for transport, but the elastic-ci-stack-s3-secrets-hooks plugin did not find any SSH keys in the "buildkite-bucket-name" S3 bucket.`

I'm inclined to believe that the parameters in SSM, in this case, aren't being grabbed at all.
